name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  - repository: vmchooserbackendv3
    type: github
    name: vmchooser/azure-vmchooser-backend-v3
    endpoint: vmchooser
trigger: 
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /terraform/
    - /scripts/
    - /.pipelines/templates/tf*
stages:
- stage: Package
  displayName: Package Files
  jobs:
  - job: Package
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'vmchooserlandscapeserverless'
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build_Shared
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: vmchooserfrontendpreview
    - template: ../templates/tf-environment-build.yml
      parameters:
        module: shared
        stage: shared
  - job: Build_Core
    dependsOn: Build_Shared
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ../templates/tf-environment-build.yml
      parameters:
        module: core
        stage: dev
  - job: Build_Serverless
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ../templates/tf-environment-build.yml
      parameters:
        module: serverless
        stage: dev
- stage: DeployCore
  displayName: Deploy Core - Shared Components
  dependsOn: Build
  jobs: 
    - deployment: DeployPrd
      variables:
      - group: vmchooser
      environment: 'vmchoosershared'
      strategy: 
        runOnce:
          deploy:          
            pool: 
              vmImage: 'ubuntu-latest'
            steps:
            - template: ../templates/tf-environment-deploy.yml
              parameters:
                varfile: ../environments/shared.tfvars
                stage: shared
                module: shared
- stage: DeployDev
  displayName: Deploy Development Environment
  dependsOn: DeployCore
  jobs: 
    - deployment: Deploy_Dev_Core
      variables:
      - group: vmchooser
      environment: 'vmchooserdev'
      strategy: 
        runOnce:
          deploy:          
            pool: 
              vmImage: 'ubuntu-latest'
            steps:
            - template: ../templates/tf-environment-deploy.yml
              parameters:
                varfile: ../environments/dev.tfvars
                stage: dev
                module: core
    - deployment: Deploy_Dev_Serverless
      dependsOn: Deploy_Dev_Core
      variables:
      - group: vmchooser
      environment: 'vmchooserdev'
      strategy: 
        runOnce:
          deploy:          
            pool: 
              vmImage: 'ubuntu-latest'
            steps:
            - template: ../templates/tf-environment-deploy.yml
              parameters:
                varfile: ../environments/dev.tfvars
                stage: dev
                module: serverless
- stage: DeployPrd
  displayName: Deploy Production Environment
  dependsOn: DeployDev
  jobs: 
    - deployment: Deploy_Prd_Core
      variables:
      - group: vmchooser
      environment: 'vmchooserprd'
      strategy: 
        runOnce:
          deploy:          
            pool: 
              vmImage: 'ubuntu-latest'
            steps:
            - template: ../templates/tf-environment-deploy.yml
              parameters:
                varfile: ../environments/prd.tfvars
                stage: prd
                module: core
    - deployment: Deploy_Prd_Serverless
      dependsOn: Deploy_Prd_Core
      variables:
      - group: vmchooser
      environment: 'vmchooserprd'
      strategy: 
        runOnce:
          deploy:          
            pool: 
              vmImage: 'ubuntu-latest'
            steps:
            - template: ../templates/tf-environment-deploy.yml
              parameters:
                varfile: ../environments/prd.tfvars
                stage: prd
                module: serverless